'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClientSpecificFee
    Public Property ProfileNumber As String
    Public Property FullName As String
    Public Property SF_DOM As Nullable(Of Decimal)
    Public Property SF_REG As Nullable(Of Decimal)
    Public Property SF_INTL As Nullable(Of Decimal)
    Public Property SF_DOM_CURR As String
    Public Property SF_REG_CURR As String
    Public Property SF_INTL_CURR As String
    Public Property IF_CONVERT As String
    Public Property WITH_VAT As String
    Public Property SF_DOM_LCC As Nullable(Of Decimal)
    Public Property SF_DOM_LCC_CURR As String
    Public Property SF_AOH As Nullable(Of Decimal)
    Public Property SF_AOH_CURR As String
    Public Property ID As Integer

End Class
