'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClientSpecific
    Public Property ClientID As Nullable(Of Decimal)
    Public Property ClientName As String
    Public Property PartnerCode As String
    Public Property AgencyIATA As String
    Public Property SMDID As String
    Public Property TSPID As String
    Public Property GlobalCustNo As String
    Public Property LocalCustNo_MIS As String
    Public Property LocalCustNo As String
    Public Property EmployeeNo As String
    Public Property TravellerName As String
    Public Property TravellerStatus As String
    Public Property CostCenterCode As String
    Public Property ProjectNo As String
    Public Property DepartmentNo As String
    Public Property OrderRef As String
    Public Property Approver As String
    Public Property ApprovalCode As String
    Public Property MgrSuperior As String
    Public Property ReasonofTrip As String
    Public Property CarrierCD As String
    Public Property validatingCarrierCD As String
    Public Property PNRSegmentNo As String
    Public Property OPRFltNo As String
    Public Property MajorClass As String
    Public Property [Class] As String
    Public Property FareBasis As String
    Public Property TKTType As String
    Public Property TktNo As String
    Public Property NoofDoc As String
    Public Property GDSReloc As String
    Public Property StopOvrFlag As String
    Public Property TourCode As String
    Public Property Itinerary As String
    Public Property LocCur As String
    Public Property FullFare As String
    Public Property FarePaid As String
    Public Property LocTax As String
    Public Property lowFare As String
    Public Property ReasonCode As String
    Public Property ReasonCodeDenied As String
    Public Property CustomerSpecFullFare As String
    Public Property CustomerSpecLowFare As String
    Public Property TrxFee As String
    Public Property RefundedFare As String
    Public Property RetAirCommAmt As String
    Public Property FFlyrNo As String
    Public Property HotelBookedFlag As String
    Public Property AirNoAccomodationReasconCode As String
    Public Property HotelName As String
    Public Property Address As String
    Public Property CtyCtrCodeZip As String
    Public Property CheckIndate As String
    Public Property NoofGuests As String
    Public Property HotelChainCode As String
    Public Property HotelGDSPartnerCD As String
    Public Property GDSrmtype As String
    Public Property RMType As String
    Public Property HotelVoucherCur As String
    Public Property RateTypeCode As String
    Public Property AreaCode As String
    Public Property NightStay As String
    Public Property RoomRateCur As String
    Public Property FullRoomRatePerNight As String
    Public Property PaidRoomRatePerNight As String
    Public Property LowRoomRatePerNight As String
    Public Property RetHotelCommAmt As String
    Public Property HotelReasonCode As String
    Public Property HotelReasonCodeDenied As String
    Public Property CustomerSpecFullRate As String
    Public Property CustomerSpecLowRate As String
    Public Property HotelBookMode As String
    Public Property CarBookedFlag As String
    Public Property SupplierName As String
    Public Property GDSMasterSuppCode As String
    Public Property CarGDSPartnerCDUsed As String
    Public Property GDSCarTypeCode As String
    Public Property CarVoucherNo As String
    Public Property RentalDays As String
    Public Property CarRentRateCur As String
    Public Property FullCarRentRatePerDay As String
    Public Property PaidCarRentRatePerDay As String
    Public Property LowCarRentRatePerDay As String
    Public Property CarReasonCode As String
    Public Property CarReasonCodeDenied As String
    Public Property CarBookMode As String
    Public Property PickUpDate As String
    Public Property CarPickUPAptCD As String
    Public Property RetCarCommAmt As String
    Public Property SalesInvDate As String
    Public Property SalesInvNo As String
    Public Property SalesChannel As String
    Public Property RecordType As String
    Public Property CSData1 As String
    Public Property COData1 As String
    Public Property CSData2 As String
    Public Property COData2 As String
    Public Property CSData3 As String
    Public Property COData3 As String
    Public Property CSData4 As String
    Public Property COData4 As String
    Public Property CSData5 As String
    Public Property CSData6 As String
    Public Property CSData7 As String
    Public Property CSData8 As String
    Public Property CSData9 As String
    Public Property CSData10 As String
    Public Property CSData11 As String
    Public Property CSData12 As String
    Public Property CustoSpecLF As String
    Public Property CustoSpecRFAmount As String
    Public Property TempPKID As Integer
    Public Property Id As Integer

End Class
