'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClientListBI
    Public Property ClientNo As String
    Public Property AccountName As String
    Public Property CreditTerm As String
    Public Property PaymentForm As String
    Public Property GovTaxonSF As String
    Public Property AcctBiller As String
    Public Property Remarks As String
    Public Property ID As Integer

End Class
