'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CreditCardDetail
    Public Property ClientName As String
    Public Property ClientNo As String
    Public Property CreditCardNo As String
    Public Property ExpirationDateMonth As String
    Public Property ExpirationDateYear As String
    Public Property ApproverNo As String
    Public Property Remarks As String
    Public Property ID As Integer

End Class
