'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Departments
    Public Property DepartmentID As Decimal
    Public Property ProfileNumber As String
    Public Property DepartmentCode As String
    Public Property DepartmentName As String
    Public Property Contact As String
    Public Property PhoneNumber As String
    Public Property FaxNumber As String
    Public Property Email As String
    Public Property Budget As Decimal

End Class
