'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GRO_AgencyProfile_PP
    Public Property AgencyNo As String
    Public Property AgencyName As String
    Public Property SortName As String
    Public Property Address1 As String
    Public Property Address2 As String
    Public Property Street As String
    Public Property ZipCode As String
    Public Property City As String
    Public Property StateCode As String
    Public Property CountryCode As String
    Public Property ContactPerson As String
    Public Property PhoneNumber As String
    Public Property FaxNumber As String
    Public Property EmailAddress As String
    Public Property GDS As String
    Public Property MajorAgencyNo As String
    Public Property InternalAgencyNo As String
    Public Property NotinUse403 As String
    Public Property NotinUse419 As String
    Public Property NotinUse435 As String
    Public Property NotinUse451 As String
    Public Property NotinUse467 As String
    Public Property ID As Integer

End Class
