'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GRO_ClientProfile_CP
    Public Property PartnerCode As String
    Public Property GlobalCustNo As String
    Public Property LocalCustNo As String
    Public Property CompanyName As String
    Public Property SortName As String
    Public Property Address1 As String
    Public Property Address2 As String
    Public Property Street As String
    Public Property City As String
    Public Property ZipCode As String
    Public Property StateCode As String
    Public Property CountryCode As String
    Public Property Remarks As String
    Public Property ContactPerson As String
    Public Property PhoneNo As String
    Public Property FaxNo As String
    Public Property EmailAddress As String
    Public Property Status As String
    Public Property LocalConcernName As String
    Public Property AcctgMgrName As String
    Public Property LocalConcernNo As String
    Public Property SalesOffice As String
    Public Property TeamCode As String
    Public Property GlobalCustCode As String
    Public Property ExtrnalCltNo As String
    Public Property CustomerCat As String
    Public Property AcctMgrCode As String
    Public Property LocalCltGrp As String
    Public Property LocalHierarchy1 As String
    Public Property LocalHierarchy2 As String
    Public Property FeeModelCode As String
    Public Property Notinuse497 As String
    Public Property Notinuse513 As String
    Public Property Notinuse529 As String
    Public Property Notinuse545 As String
    Public Property Notinuse561 As String
    Public Property ID As Integer

End Class
