'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GROExtraction
    Public Property InvoiceNo As String
    Public Property InvoiceDate As String
    Public Property Extracted As String
    Public Property Remarks As String
    Public Property ID As Integer

End Class
