'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class TravComEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TravComEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Airlines() As DbSet(Of Airlines)
    Public Overridable Property Departments() As DbSet(Of Departments)
    Public Overridable Property Divisions() As DbSet(Of Divisions)
    Public Overridable Property ProductCodes() As DbSet(Of ProductCodes)
    Public Overridable Property Profiles() As DbSet(Of Profiles)
    Public Overridable Property Currencies() As DbSet(Of Currencies)

End Class
