'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MIDFields
    Public Property ClientGCN As String
    Public Property DataItem As String
    Public Property Gems As String
    Public Property Required As String
    Public Property List As String
    Public Property DataType As String
    Public Property Length As String
    Public Property CustomerFieldName As String
    Public Property ID As Integer

End Class
