'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class NonAirTransaction
    Public Property ProductCode As String
    Public Property SubProduct As String
    Public Property CP As String
    Public Property CPAccess As String
    Public Property VendorCode As String
    Public Property VendorAccess As String
    Public Property Cost As String
    Public Property CostAccess As String
    Public Property SAAmount As String
    Public Property SAAccess As String
    Public Property Remarks As String
    Public Property travelType As String
    Public Property RefFare As String
    Public Property LowFare As String
    Public Property EC As String
    Public Property DateHotel As String
    Public Property ID As Integer

End Class
