'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductCodes
    Public Property ProductCode As Byte
    Public Property Description As String
    Public Property Controlled As Boolean
    Public Property TicketFormat As String
    Public Property Itinerary As Boolean
    Public Property ReceivableAccount As String
    Public Property PayableAccount As String
    Public Property IncomeAccount As String
    Public Property ExpenseAccount As String
    Public Property VatCode As String
    Public Property TravelType As Byte

End Class
