'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProductSetting
    Public Property ProductName As String
    Public Property ProductCategory As String
    Public Property Remarks As String
    Public Property SubProdAccess As String
    Public Property CommPercentage As String
    Public Property CommAccess As String
    Public Property Vendor As String
    Public Property VendorAccess As String
    Public Property CostAmount As String
    Public Property CostAccess As String
    Public Property SFAmount As String
    Public Property SFAccess As String
    Public Property ID As Integer

End Class
