'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Profiles
    Public Property ProfileID As Decimal
    Public Property ProfileType As Byte
    Public Property ProfileNumber As String
    Public Property InterfaceCode As String
    Public Property AccountType As Byte
    Public Property Prefix As String
    Public Property FirstName As String
    Public Property LastName As String
    Public Property FullName As String
    Public Property Salutation As String
    Public Property PhoneType1 As String
    Public Property PhoneType2 As String
    Public Property PhoneType3 As String
    Public Property PhoneType4 As String
    Public Property PhoneType5 As String
    Public Property PhoneNumber1 As String
    Public Property PhoneNumber2 As String
    Public Property PhoneNumber3 As String
    Public Property PhoneNumber4 As String
    Public Property PhoneNumber5 As String
    Public Property PhoneSort1 As String
    Public Property PhoneSort2 As String
    Public Property PhoneSort3 As String
    Public Property PhoneSort4 As String
    Public Property PhoneSort5 As String
    Public Property Language As Byte
    Public Property FirstDate As Nullable(Of Date)
    Public Property LastDate As Nullable(Of Date)
    Public Property UpdateDate As Nullable(Of Date)
    Public Property Balance As Decimal
    Public Property AddedBy As Decimal
    Public Property Active As Boolean
    Public Property SendEmail As Boolean
    Public Property CBSync As Boolean
    Public Property Notes As String
    Public Property Branches As String

End Class
