'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProfileAgentInfo
    Public Property First_Name As String
    Public Property Last_Name As String
    Public Property InitialSignIn As String
    Public Property QueueNo As String
    Public Property TeamGroup As String
    Public Property ContactNo As String
    Public Property AP As String
    Public Property Div As String
    Public Property CompanyName As String
    Public Property Remarks As String
    Public Property Others As String
    Public Property Status As String
    Public Property AccessLevel As String
    Public Property CreditCardAccess As String
    Public Property GDSSignIn As String
    Public Property DivisionNo As String
    Public Property ID As Integer

End Class
