'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class T_MgrSup
    Public Property ClientID As String
    Public Property GCN As String
    Public Property BCD_Code As String
    Public Property ABR_Code As String
    Public Property FieldName As String
    Public Property ID As Integer

End Class
