'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class TAISLocalEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TAISLocalEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CAPIAccesses() As DbSet(Of CAPIAccess)
    Public Overridable Property CreditCardDetails() As DbSet(Of CreditCardDetail)
    Public Overridable Property CreditMonitorings() As DbSet(Of CreditMonitoring)
    Public Overridable Property NonAirTransactions() As DbSet(Of NonAirTransaction)
    Public Overridable Property ProductSettings() As DbSet(Of ProductSetting)
    Public Overridable Property ProfileAgentInfoes() As DbSet(Of ProfileAgentInfo)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property Transmittals() As DbSet(Of Transmittal)
    Public Overridable Property UserAccesses() As DbSet(Of UserAccess)
    Public Overridable Property Users() As DbSet(Of User)
    Public Overridable Property Vessels() As DbSet(Of Vessel)

End Class
