'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Transmittal
    Public Property ProfileNo As String
    Public Property InvoiceNo As String
    Public Property InvoiceDate As Nullable(Of Date)
    Public Property InvoiceAmount As String
    Public Property AttentionTo As String
    Public Property PreparedBy As String
    Public Property ReceivedBy As String
    Public Property DateReleased As Nullable(Of Date)
    Public Property DateReceived As Nullable(Of Date)
    Public Property ID As Integer

End Class
