'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserAccess
    Public Property AccessLevel As String
    Public Property ClientNo As String
    Public Property DivisionNo As String
    Public Property BookingAgent As String
    Public Property VesselName As String
    Public Property PhoneElement As String
    Public Property Compleat As String
    Public Property ReceivedFrom As String
    Public Property TKTL As String
    Public Property ClientName As String
    Public Property VName As String
    Public Property BillTo As String
    Public Property Mandatory As String
    Public Property DivNo As String
    Public Property ID As Integer

End Class
