'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace SessionManager
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LogonRequestData", [Namespace]:="http://schemas.navitaire.com/WebServices/DataContracts/Session"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LogonRequestData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DomainCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AgentNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RoleCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TerminalInfoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DomainCode() As String
            Get
                Return Me.DomainCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DomainCodeField, value) <> true) Then
                    Me.DomainCodeField = value
                    Me.RaisePropertyChanged("DomainCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public Property AgentName() As String
            Get
                Return Me.AgentNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AgentNameField, value) <> true) Then
                    Me.AgentNameField = value
                    Me.RaisePropertyChanged("AgentName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Property LocationCode() As String
            Get
                Return Me.LocationCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationCodeField, value) <> true) Then
                    Me.LocationCodeField = value
                    Me.RaisePropertyChanged("LocationCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property RoleCode() As String
            Get
                Return Me.RoleCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RoleCodeField, value) <> true) Then
                    Me.RoleCodeField = value
                    Me.RaisePropertyChanged("RoleCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Property TerminalInfo() As String
            Get
                Return Me.TerminalInfoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TerminalInfoField, value) <> true) Then
                    Me.TerminalInfoField = value
                    Me.RaisePropertyChanged("TerminalInfo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TokenRequest", [Namespace]:="http://schemas.navitaire.com/WebServices/DataContracts/Session"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TokenRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TokenField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TerminalInfoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ChannelTypeField As SessionManager.ChannelType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SystemTypeField As SessionManager.SystemType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Token() As String
            Get
                Return Me.TokenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TokenField, value) <> true) Then
                    Me.TokenField = value
                    Me.RaisePropertyChanged("Token")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public Property TerminalInfo() As String
            Get
                Return Me.TerminalInfoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TerminalInfoField, value) <> true) Then
                    Me.TerminalInfoField = value
                    Me.RaisePropertyChanged("TerminalInfo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public Property ChannelType() As SessionManager.ChannelType
            Get
                Return Me.ChannelTypeField
            End Get
            Set
                If (Me.ChannelTypeField.Equals(value) <> true) Then
                    Me.ChannelTypeField = value
                    Me.RaisePropertyChanged("ChannelType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Property SystemType() As SessionManager.SystemType
            Get
                Return Me.SystemTypeField
            End Get
            Set
                If (Me.SystemTypeField.Equals(value) <> true) Then
                    Me.SystemTypeField = value
                    Me.RaisePropertyChanged("SystemType")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ChannelType", [Namespace]:="http://schemas.navitaire.com/WebServices/DataContracts/Common/Enumerations")>  _
    Public Enum ChannelType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [Default] = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Direct = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Web = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        GDS = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        API = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Unmapped = -1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SystemType", [Namespace]:="http://schemas.navitaire.com/WebServices/DataContracts/Common/Enumerations")>  _
    Public Enum SystemType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [Default] = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        WinRez = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FareManager = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ScheduleManager = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        WinManager = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ConsoleRez = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        WebRez = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        WebServicesAPI = 7
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        WebServicesESC = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        InternalService = 9
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        WebReporting = 10
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        TaxAndFeeManager = 11
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DCS = 12
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Unmapped = -1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TransferSessionResponseData", [Namespace]:="http://schemas.navitaire.com/WebServices/DataContracts/Session"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TransferSessionResponseData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SignatureField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Signature() As String
            Get
                Return Me.SignatureField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SignatureField, value) <> true) Then
                    Me.SignatureField = value
                    Me.RaisePropertyChanged("Signature")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.navitaire.com/WebServices", ConfigurationName:="SessionManager.ISessionManager")>  _
    Public Interface ISessionManager
        
        'CODEGEN: Generating message contract since the operation ChangePassword is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePassword", ReplyAction:="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordResponse")>  _
        Function ChangePassword(ByVal request As SessionManager.ChangePasswordRequest) As SessionManager.ChangePasswordResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService) of message LogonRequest does not match the default value (http://schemas.navitaire.com/WebServices)
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.navitaire.com/WebServices/ISessionManager/Logon", ReplyAction:="http://schemas.navitaire.com/WebServices/ISessionManager/LogonResponse")>  _
        Function Logon(ByVal request As SessionManager.LogonRequest) As SessionManager.LogonResponse
        
        'CODEGEN: Generating message contract since the operation Logout is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.navitaire.com/WebServices/ISessionManager/Logout", ReplyAction:="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutResponse")>  _
        Function Logout(ByVal request As SessionManager.LogoutRequest) As SessionManager.LogoutResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService) of message TransferSessionRequest does not match the default value (http://schemas.navitaire.com/WebServices)
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSession", ReplyAction:="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionResponse")>  _
        Function TransferSession(ByVal request As SessionManager.TransferSessionRequest) As SessionManager.TransferSessionResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ChangePasswordRequest", WrapperNamespace:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped:=true)>  _
    Partial Public Class ChangePasswordRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public ContractVersion As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order:=0)>  _
        Public logonRequestData As SessionManager.LogonRequestData
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order:=1)>  _
        Public newPassword As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ContractVersion As Integer, ByVal logonRequestData As SessionManager.LogonRequestData, ByVal newPassword As String)
            MyBase.New
            Me.ContractVersion = ContractVersion
            Me.logonRequestData = logonRequestData
            Me.newPassword = newPassword
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ChangePasswordResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="LogonRequest", WrapperNamespace:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped:=true)>  _
    Partial Public Class LogonRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public ContractVersion As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order:=0)>  _
        Public logonRequestData As SessionManager.LogonRequestData
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ContractVersion As Integer, ByVal logonRequestData As SessionManager.LogonRequestData)
            MyBase.New
            Me.ContractVersion = ContractVersion
            Me.logonRequestData = logonRequestData
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="LogonResponse", WrapperNamespace:="http://schemas.navitaire.com/WebServices", IsWrapped:=true)>  _
    Partial Public Class LogonResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.navitaire.com/WebServices", Order:=0)>  _
        Public Signature As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Signature As String)
            MyBase.New
            Me.Signature = Signature
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="LogoutRequest", WrapperNamespace:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped:=true)>  _
    Partial Public Class LogoutRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public ContractVersion As Integer
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public Signature As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ContractVersion As Integer, ByVal Signature As String)
            MyBase.New
            Me.ContractVersion = ContractVersion
            Me.Signature = Signature
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LogoutResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="TransferSessionRequest", WrapperNamespace:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped:=true)>  _
    Partial Public Class TransferSessionRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public ContractVersion As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order:=0)>  _
        Public tokenRequest As SessionManager.TokenRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ContractVersion As Integer, ByVal tokenRequest As SessionManager.TokenRequest)
            MyBase.New
            Me.ContractVersion = ContractVersion
            Me.tokenRequest = tokenRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="TransferSessionResponse", WrapperNamespace:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped:=true)>  _
    Partial Public Class TransferSessionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order:=0)>  _
        Public TransferSessionResponseData As SessionManager.TransferSessionResponseData
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TransferSessionResponseData As SessionManager.TransferSessionResponseData)
            MyBase.New
            Me.TransferSessionResponseData = TransferSessionResponseData
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISessionManagerChannel
        Inherits SessionManager.ISessionManager, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SessionManagerClient
        Inherits System.ServiceModel.ClientBase(Of SessionManager.ISessionManager)
        Implements SessionManager.ISessionManager
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SessionManager_ISessionManager_ChangePassword(ByVal request As SessionManager.ChangePasswordRequest) As SessionManager.ChangePasswordResponse Implements SessionManager.ISessionManager.ChangePassword
            Return MyBase.Channel.ChangePassword(request)
        End Function
        
        Public Sub ChangePassword(ByVal ContractVersion As Integer, ByVal logonRequestData As SessionManager.LogonRequestData, ByVal newPassword As String)
            Dim inValue As SessionManager.ChangePasswordRequest = New SessionManager.ChangePasswordRequest()
            inValue.ContractVersion = ContractVersion
            inValue.logonRequestData = logonRequestData
            inValue.newPassword = newPassword
            Dim retVal As SessionManager.ChangePasswordResponse = CType(Me,SessionManager.ISessionManager).ChangePassword(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SessionManager_ISessionManager_Logon(ByVal request As SessionManager.LogonRequest) As SessionManager.LogonResponse Implements SessionManager.ISessionManager.Logon
            Return MyBase.Channel.Logon(request)
        End Function
        
        Public Function Logon(ByVal ContractVersion As Integer, ByVal logonRequestData As SessionManager.LogonRequestData) As String
            Dim inValue As SessionManager.LogonRequest = New SessionManager.LogonRequest()
            inValue.ContractVersion = ContractVersion
            inValue.logonRequestData = logonRequestData
            Dim retVal As SessionManager.LogonResponse = CType(Me,SessionManager.ISessionManager).Logon(inValue)
            Return retVal.Signature
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SessionManager_ISessionManager_Logout(ByVal request As SessionManager.LogoutRequest) As SessionManager.LogoutResponse Implements SessionManager.ISessionManager.Logout
            Return MyBase.Channel.Logout(request)
        End Function
        
        Public Sub Logout(ByVal ContractVersion As Integer, ByVal Signature As String)
            Dim inValue As SessionManager.LogoutRequest = New SessionManager.LogoutRequest()
            inValue.ContractVersion = ContractVersion
            inValue.Signature = Signature
            Dim retVal As SessionManager.LogoutResponse = CType(Me,SessionManager.ISessionManager).Logout(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SessionManager_ISessionManager_TransferSession(ByVal request As SessionManager.TransferSessionRequest) As SessionManager.TransferSessionResponse Implements SessionManager.ISessionManager.TransferSession
            Return MyBase.Channel.TransferSession(request)
        End Function
        
        Public Function TransferSession(ByVal ContractVersion As Integer, ByVal tokenRequest As SessionManager.TokenRequest) As SessionManager.TransferSessionResponseData
            Dim inValue As SessionManager.TransferSessionRequest = New SessionManager.TransferSessionRequest()
            inValue.ContractVersion = ContractVersion
            inValue.tokenRequest = tokenRequest
            Dim retVal As SessionManager.TransferSessionResponse = CType(Me,SessionManager.ISessionManager).TransferSession(inValue)
            Return retVal.TransferSessionResponseData
        End Function
    End Class
End Namespace
