'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace SessionManager
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts")>  _
    Partial Public Class APIUnhandledServerFault
        Inherits APIWarningFault
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(APIUnhandledServerFault)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts")>  _
    Partial Public Class APIWarningFault
        Inherits APIFault
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(APIValidationFault)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(APICriticalFault)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(APISecurityFault)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(APIGeneralFault)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(APIWarningFault)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(APIUnhandledServerFault)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts")>  _
    Partial Public Class APIFault
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private errorCodeField As String
        
        Private errorTypeField As String
        
        Private messageField As String
        
        Private uniqueIDField As String
        
        Private stackTraceField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property ErrorCode() As String
            Get
                Return Me.errorCodeField
            End Get
            Set
                Me.errorCodeField = value
                Me.RaisePropertyChanged("ErrorCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property ErrorType() As String
            Get
                Return Me.errorTypeField
            End Get
            Set
                Me.errorTypeField = value
                Me.RaisePropertyChanged("ErrorType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("Message")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property UniqueID() As String
            Get
                Return Me.uniqueIDField
            End Get
            Set
                Me.uniqueIDField = value
                Me.RaisePropertyChanged("UniqueID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property StackTrace() As String
            Get
                Return Me.stackTraceField
            End Get
            Set
                Me.stackTraceField = value
                Me.RaisePropertyChanged("StackTrace")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.navitaire.com/Ncl/Validation/ValidationResult")>  _
    Partial Public Class ValidationResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private annotationsField As System.Data.DataSet
        
        Private failedValidationDescriptionField As String
        
        Private keyField As String
        
        Private successfulField As Boolean
        
        Private successfulFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property Annotations() As System.Data.DataSet
            Get
                Return Me.annotationsField
            End Get
            Set
                Me.annotationsField = value
                Me.RaisePropertyChanged("Annotations")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property FailedValidationDescription() As String
            Get
                Return Me.failedValidationDescriptionField
            End Get
            Set
                Me.failedValidationDescriptionField = value
                Me.RaisePropertyChanged("FailedValidationDescription")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
                Me.RaisePropertyChanged("Key")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Successful() As Boolean
            Get
                Return Me.successfulField
            End Get
            Set
                Me.successfulField = value
                Me.RaisePropertyChanged("Successful")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SuccessfulSpecified() As Boolean
            Get
                Return Me.successfulFieldSpecified
            End Get
            Set
                Me.successfulFieldSpecified = value
                Me.RaisePropertyChanged("SuccessfulSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/DataContracts/Session")>  _
    Partial Public Class LogonRequestData
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private domainCodeField As String
        
        Private agentNameField As String
        
        Private passwordField As String
        
        Private locationCodeField As String
        
        Private roleCodeField As String
        
        Private terminalInfoField As String
        
        Private clientNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property DomainCode() As String
            Get
                Return Me.domainCodeField
            End Get
            Set
                Me.domainCodeField = value
                Me.RaisePropertyChanged("DomainCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property AgentName() As String
            Get
                Return Me.agentNameField
            End Get
            Set
                Me.agentNameField = value
                Me.RaisePropertyChanged("AgentName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("Password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property LocationCode() As String
            Get
                Return Me.locationCodeField
            End Get
            Set
                Me.locationCodeField = value
                Me.RaisePropertyChanged("LocationCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property RoleCode() As String
            Get
                Return Me.roleCodeField
            End Get
            Set
                Me.roleCodeField = value
                Me.RaisePropertyChanged("RoleCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property TerminalInfo() As String
            Get
                Return Me.terminalInfoField
            End Get
            Set
                Me.terminalInfoField = value
                Me.RaisePropertyChanged("TerminalInfo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=6)>  _
        Public Property ClientName() As String
            Get
                Return Me.clientNameField
            End Get
            Set
                Me.clientNameField = value
                Me.RaisePropertyChanged("ClientName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts")>  _
    Partial Public Class APIValidationFault
        Inherits APIFault
        
        Private validationResultsField() As ValidationResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=0),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://www.navitaire.com/Ncl/Validation/ValidationResult")>  _
        Public Property ValidationResults() As ValidationResult()
            Get
                Return Me.validationResultsField
            End Get
            Set
                Me.validationResultsField = value
                Me.RaisePropertyChanged("ValidationResults")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts")>  _
    Partial Public Class APICriticalFault
        Inherits APIFault
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts")>  _
    Partial Public Class APISecurityFault
        Inherits APIFault
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts")>  _
    Partial Public Class APIGeneralFault
        Inherits APIFault
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.navitaire.com/WebServices", ConfigurationName:="SessionManager.ISessionManager")>  _
    Public Interface ISessionManager
        
        'CODEGEN: Generating message contract since the operation ChangePassword is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePassword", ReplyAction:="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIUnhandledServerFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPIUnhandl"& _ 
            "edServerFaultFault", Name:="APIUnhandledServerFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIGeneralFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPIGeneral"& _ 
            "FaultFault", Name:="APIGeneralFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPIFaultFa"& _ 
            "ult", Name:="APIFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIWarningFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPIWarning"& _ 
            "FaultFault", Name:="APIWarningFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APISecurityFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPISecurit"& _ 
            "yFaultFault", Name:="APISecurityFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APICriticalFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPICritica"& _ 
            "lFaultFault", Name:="APICriticalFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIValidationFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/ChangePasswordAPIValidat"& _ 
            "ionFaultFault", Name:="APIValidationFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(APIFault))>  _
        Function ChangePassword(ByVal request As SessionManager.ChangePasswordRequest) As SessionManager.ChangePasswordResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService) of message LogonRequest does not match the default value (http://schemas.navitaire.com/WebServices)
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.navitaire.com/WebServices/ISessionManager/Logon", ReplyAction:="http://schemas.navitaire.com/WebServices/ISessionManager/LogonResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIWarningFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPIWarningFaultFaul"& _ 
            "t", Name:="APIWarningFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPIFaultFault", Name:="APIFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APICriticalFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPICriticalFaultFau"& _ 
            "lt", Name:="APICriticalFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIGeneralFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPIGeneralFaultFaul"& _ 
            "t", Name:="APIGeneralFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIValidationFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPIValidationFaultF"& _ 
            "ault", Name:="APIValidationFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APISecurityFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPISecurityFaultFau"& _ 
            "lt", Name:="APISecurityFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIUnhandledServerFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogonAPIUnhandledServerF"& _ 
            "aultFault", Name:="APIUnhandledServerFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(APIFault))>  _
        Function Logon(ByVal request As SessionManager.LogonRequest) As SessionManager.LogonResponse
        
        'CODEGEN: Generating message contract since the operation Logout is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.navitaire.com/WebServices/ISessionManager/Logout", ReplyAction:="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APICriticalFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPICriticalFaultFa"& _ 
            "ult", Name:="APICriticalFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APISecurityFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPISecurityFaultFa"& _ 
            "ult", Name:="APISecurityFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIGeneralFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPIGeneralFaultFau"& _ 
            "lt", Name:="APIGeneralFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIValidationFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPIValidationFault"& _ 
            "Fault", Name:="APIValidationFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIWarningFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPIWarningFaultFau"& _ 
            "lt", Name:="APIWarningFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPIFaultFault", Name:="APIFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIUnhandledServerFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/LogoutAPIUnhandledServer"& _ 
            "FaultFault", Name:="APIUnhandledServerFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(APIFault))>  _
        Function Logout(ByVal request As SessionManager.LogoutRequest) As SessionManager.LogoutResponse
        
        'CODEGEN: Generating message contract since the wrapper namespace (http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService) of message TransferSessionRequest does not match the default value (http://schemas.navitaire.com/WebServices)
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSession", ReplyAction:="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIValidationFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPIValida"& _ 
            "tionFaultFault", Name:="APIValidationFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APICriticalFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPICritic"& _ 
            "alFaultFault", Name:="APICriticalFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIWarningFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPIWarnin"& _ 
            "gFaultFault", Name:="APIWarningFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIUnhandledServerFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPIUnhand"& _ 
            "ledServerFaultFault", Name:="APIUnhandledServerFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPIFaultF"& _ 
            "ault", Name:="APIFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APISecurityFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPISecuri"& _ 
            "tyFaultFault", Name:="APISecurityFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.FaultContractAttribute(GetType(SessionManager.APIGeneralFault), Action:="http://schemas.navitaire.com/WebServices/ISessionManager/TransferSessionAPIGenera"& _ 
            "lFaultFault", Name:="APIGeneralFault", [Namespace]:="http://schemas.navitaire.com/WebServices/FaultContracts"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(APIFault))>  _
        Function TransferSession(ByVal request As SessionManager.TransferSessionRequest) As SessionManager.TransferSessionResponse
        
        'CODEGEN: Generating message contract since the operation KeepAlive is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.navitaire.com/WebServices/ISessionManager/KeepAlive", ReplyAction:="http://schemas.navitaire.com/WebServices/ISessionManager/KeepAliveResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(APIFault))>  _
        Function KeepAlive(ByVal request As SessionManager.KeepAliveRequest) As SessionManager.KeepAliveResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="ChangePasswordRequest", WrapperNamespace:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped:=true)>  _
    Partial Public Class ChangePasswordRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public ContractVersion As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public logonRequestData As SessionManager.LogonRequestData
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public newPassword As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ContractVersion As Integer, ByVal logonRequestData As SessionManager.LogonRequestData, ByVal newPassword As String)
            MyBase.New
            Me.ContractVersion = ContractVersion
            Me.logonRequestData = logonRequestData
            Me.newPassword = newPassword
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ChangePasswordResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="LogonRequest", WrapperNamespace:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped:=true)>  _
    Partial Public Class LogonRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public ContractVersion As Integer
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public EnableExceptionStackTrace As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public logonRequestData As SessionManager.LogonRequestData
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ContractVersion As Integer, ByVal EnableExceptionStackTrace As Boolean, ByVal logonRequestData As SessionManager.LogonRequestData)
            MyBase.New
            Me.ContractVersion = ContractVersion
            Me.EnableExceptionStackTrace = EnableExceptionStackTrace
            Me.logonRequestData = logonRequestData
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="LogonResponse", WrapperNamespace:="http://schemas.navitaire.com/WebServices", IsWrapped:=true)>  _
    Partial Public Class LogonResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.navitaire.com/WebServices", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Signature As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Signature As String)
            MyBase.New
            Me.Signature = Signature
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="LogoutRequest", WrapperNamespace:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped:=true)>  _
    Partial Public Class LogoutRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public ContractVersion As Integer
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public EnableExceptionStackTrace As Boolean
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices"),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public MessageContractVersion As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices"),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Signature As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ContractVersion As Integer, ByVal EnableExceptionStackTrace As Boolean, ByVal MessageContractVersion As String, ByVal Signature As String)
            MyBase.New
            Me.ContractVersion = ContractVersion
            Me.EnableExceptionStackTrace = EnableExceptionStackTrace
            Me.MessageContractVersion = MessageContractVersion
            Me.Signature = Signature
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LogoutResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/DataContracts/Session")>  _
    Partial Public Class TokenRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private tokenField As String
        
        Private terminalInfoField As String
        
        Private channelTypeField As ChannelType
        
        Private channelTypeFieldSpecified As Boolean
        
        Private systemTypeField As SystemType
        
        Private systemTypeFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
                Me.RaisePropertyChanged("Token")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property TerminalInfo() As String
            Get
                Return Me.terminalInfoField
            End Get
            Set
                Me.terminalInfoField = value
                Me.RaisePropertyChanged("TerminalInfo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ChannelType() As ChannelType
            Get
                Return Me.channelTypeField
            End Get
            Set
                Me.channelTypeField = value
                Me.RaisePropertyChanged("ChannelType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ChannelTypeSpecified() As Boolean
            Get
                Return Me.channelTypeFieldSpecified
            End Get
            Set
                Me.channelTypeFieldSpecified = value
                Me.RaisePropertyChanged("ChannelTypeSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property SystemType() As SystemType
            Get
                Return Me.systemTypeField
            End Get
            Set
                Me.systemTypeField = value
                Me.RaisePropertyChanged("SystemType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SystemTypeSpecified() As Boolean
            Get
                Return Me.systemTypeFieldSpecified
            End Get
            Set
                Me.systemTypeFieldSpecified = value
                Me.RaisePropertyChanged("SystemTypeSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/DataContracts/Common/Enumerations")>  _
    Public Enum ChannelType
        
        '''<remarks/>
        [Default]
        
        '''<remarks/>
        Direct
        
        '''<remarks/>
        Web
        
        '''<remarks/>
        GDS
        
        '''<remarks/>
        API
        
        '''<remarks/>
        Unmapped
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/DataContracts/Common/Enumerations")>  _
    Public Enum SystemType
        
        '''<remarks/>
        [Default]
        
        '''<remarks/>
        WinRez
        
        '''<remarks/>
        FareManager
        
        '''<remarks/>
        ScheduleManager
        
        '''<remarks/>
        WinManager
        
        '''<remarks/>
        ConsoleRez
        
        '''<remarks/>
        WebRez
        
        '''<remarks/>
        WebServicesAPI
        
        '''<remarks/>
        WebServicesESC
        
        '''<remarks/>
        InternalService
        
        '''<remarks/>
        WebReporting
        
        '''<remarks/>
        TaxAndFeeManager
        
        '''<remarks/>
        DCS
        
        '''<remarks/>
        Unmapped
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/DataContracts/Session")>  _
    Partial Public Class TransferSessionResponseData
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private signatureField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property Signature() As String
            Get
                Return Me.signatureField
            End Get
            Set
                Me.signatureField = value
                Me.RaisePropertyChanged("Signature")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="TransferSessionRequest", WrapperNamespace:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped:=true)>  _
    Partial Public Class TransferSessionRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public ContractVersion As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public tokenRequest As SessionManager.TokenRequest
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ContractVersion As Integer, ByVal tokenRequest As SessionManager.TokenRequest)
            MyBase.New
            Me.ContractVersion = ContractVersion
            Me.tokenRequest = tokenRequest
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="TransferSessionResponse", WrapperNamespace:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped:=true)>  _
    Partial Public Class TransferSessionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public TransferSessionResponseData As SessionManager.TransferSessionResponseData
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TransferSessionResponseData As SessionManager.TransferSessionResponseData)
            MyBase.New
            Me.TransferSessionResponseData = TransferSessionResponseData
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="KeepAliveRequest", WrapperNamespace:="http://schemas.navitaire.com/WebServices/ServiceContracts/SessionService", IsWrapped:=true)>  _
    Partial Public Class KeepAliveRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public ContractVersion As Integer
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices")>  _
        Public EnableExceptionStackTrace As Boolean
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices"),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public MessageContractVersion As String
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.navitaire.com/WebServices"),  _
         System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Signature As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ContractVersion As Integer, ByVal EnableExceptionStackTrace As Boolean, ByVal MessageContractVersion As String, ByVal Signature As String)
            MyBase.New
            Me.ContractVersion = ContractVersion
            Me.EnableExceptionStackTrace = EnableExceptionStackTrace
            Me.MessageContractVersion = MessageContractVersion
            Me.Signature = Signature
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class KeepAliveResponse
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ISessionManagerChannel
        Inherits SessionManager.ISessionManager, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SessionManagerClient
        Inherits System.ServiceModel.ClientBase(Of SessionManager.ISessionManager)
        Implements SessionManager.ISessionManager
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SessionManager_ISessionManager_ChangePassword(ByVal request As SessionManager.ChangePasswordRequest) As SessionManager.ChangePasswordResponse Implements SessionManager.ISessionManager.ChangePassword
            Return MyBase.Channel.ChangePassword(request)
        End Function
        
        Public Sub ChangePassword(ByVal ContractVersion As Integer, ByVal logonRequestData As SessionManager.LogonRequestData, ByVal newPassword As String)
            Dim inValue As SessionManager.ChangePasswordRequest = New SessionManager.ChangePasswordRequest()
            inValue.ContractVersion = ContractVersion
            inValue.logonRequestData = logonRequestData
            inValue.newPassword = newPassword
            Dim retVal As SessionManager.ChangePasswordResponse = CType(Me,SessionManager.ISessionManager).ChangePassword(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SessionManager_ISessionManager_Logon(ByVal request As SessionManager.LogonRequest) As SessionManager.LogonResponse Implements SessionManager.ISessionManager.Logon
            Return MyBase.Channel.Logon(request)
        End Function
        
        Public Function Logon(ByVal ContractVersion As Integer, ByVal EnableExceptionStackTrace As Boolean, ByVal logonRequestData As SessionManager.LogonRequestData) As String
            Dim inValue As SessionManager.LogonRequest = New SessionManager.LogonRequest()
            inValue.ContractVersion = ContractVersion
            inValue.EnableExceptionStackTrace = EnableExceptionStackTrace
            inValue.logonRequestData = logonRequestData
            Dim retVal As SessionManager.LogonResponse = CType(Me,SessionManager.ISessionManager).Logon(inValue)
            Return retVal.Signature
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SessionManager_ISessionManager_Logout(ByVal request As SessionManager.LogoutRequest) As SessionManager.LogoutResponse Implements SessionManager.ISessionManager.Logout
            Return MyBase.Channel.Logout(request)
        End Function
        
        Public Sub Logout(ByVal ContractVersion As Integer, ByVal EnableExceptionStackTrace As Boolean, ByVal MessageContractVersion As String, ByVal Signature As String)
            Dim inValue As SessionManager.LogoutRequest = New SessionManager.LogoutRequest()
            inValue.ContractVersion = ContractVersion
            inValue.EnableExceptionStackTrace = EnableExceptionStackTrace
            inValue.MessageContractVersion = MessageContractVersion
            inValue.Signature = Signature
            Dim retVal As SessionManager.LogoutResponse = CType(Me,SessionManager.ISessionManager).Logout(inValue)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SessionManager_ISessionManager_TransferSession(ByVal request As SessionManager.TransferSessionRequest) As SessionManager.TransferSessionResponse Implements SessionManager.ISessionManager.TransferSession
            Return MyBase.Channel.TransferSession(request)
        End Function
        
        Public Function TransferSession(ByVal ContractVersion As Integer, ByVal tokenRequest As SessionManager.TokenRequest) As SessionManager.TransferSessionResponseData
            Dim inValue As SessionManager.TransferSessionRequest = New SessionManager.TransferSessionRequest()
            inValue.ContractVersion = ContractVersion
            inValue.tokenRequest = tokenRequest
            Dim retVal As SessionManager.TransferSessionResponse = CType(Me,SessionManager.ISessionManager).TransferSession(inValue)
            Return retVal.TransferSessionResponseData
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function SessionManager_ISessionManager_KeepAlive(ByVal request As SessionManager.KeepAliveRequest) As SessionManager.KeepAliveResponse Implements SessionManager.ISessionManager.KeepAlive
            Return MyBase.Channel.KeepAlive(request)
        End Function
        
        Public Sub KeepAlive(ByVal ContractVersion As Integer, ByVal EnableExceptionStackTrace As Boolean, ByVal MessageContractVersion As String, ByVal Signature As String)
            Dim inValue As SessionManager.KeepAliveRequest = New SessionManager.KeepAliveRequest()
            inValue.ContractVersion = ContractVersion
            inValue.EnableExceptionStackTrace = EnableExceptionStackTrace
            inValue.MessageContractVersion = MessageContractVersion
            inValue.Signature = Signature
            Dim retVal As SessionManager.KeepAliveResponse = CType(Me,SessionManager.ISessionManager).KeepAlive(inValue)
        End Sub
    End Class
End Namespace
